# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-File-SLN
version:      0.11
version_from: lib/Chemistry/File/SLN.pm
installdirs:  site
requires:
    Chemistry::Bond::Find:         0.21
    Chemistry::Canonicalize:       0.10
    Chemistry::Mol:                0.26
    Chemistry::Ring:               0.15
    List::Util:                    0
    Parse::Yapp:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
