# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-File-SMARTS
version:      0.22
version_from: SMARTS.pm
installdirs:  site
requires:
    Chemistry::File::SMILES:       0.41
    Chemistry::Mol:                0.24
    Chemistry::Pattern:            0.25
    Chemistry::Ring:               0.16
    List::Util:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
