name: PerlMol
version: 0.3200
abstract: Perl modules for chemoinformatics and computational chemistry
author: Ivan Tubert-Brohman <itub@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  Test::Simple: 0.45
  Scalar::Util: 1.07
  Storable: 2.04
  Text::Balanced: 1.89
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
