# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-File-MDLMol
version:      0.20
version_from: MDLMol.pm
installdirs:  site
requires:
    Chemistry::Mol:                0.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
