# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-Reaction
version:      0.02
version_from: lib/Chemistry/Reaction.pm
installdirs:  site
requires:
    Chemistry::File::SMILES:       0.42
    Chemistry::Mol:                0.26
    Chemistry::Pattern:            0.25

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
