# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-MidasPattern
version:      0.11
version_from: lib/Chemistry/MidasPattern.pm
installdirs:  site
requires:
    Chemistry::File::PDB:          0.21
    Chemistry::MacroMol:           0.05
    Chemistry::Mol:                0.24
    Chemistry::Pattern:            0.20
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
