# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-InternalCoords
version:      0.18
version_from: InternalCoords.pm
installdirs:  site
requires:
    Chemistry::Bond::Find:         0.2
    Chemistry::Canonicalize:       0.1
    Chemistry::Mol:                0.25
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
