# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-FormulaPattern
version:      0.10
version_from: lib/Chemistry/FormulaPattern.pm
installdirs:  site
requires:
    Chemistry::Mol:                0.24
    Chemistry::Pattern:            0.20
    Test::More:                    0
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
