# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-3DBuilder
version:      0.10
version_from: lib/Chemistry/3DBuilder.pm
installdirs:  site
requires:
    Chemistry::File::SMARTS:       0.21
    Chemistry::File::SMILES:       0.43
    Chemistry::InternalCoords:     0.18
    Chemistry::Mol:                0.33
    Chemistry::Pattern:            0.25
    Chemistry::Ring:               0.18
    Math::VectorReal:              1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
