# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-Mol
version:      0.35
version_from: Mol.pm
installdirs:  site
requires:
    Math::VectorReal:              1
    Scalar::Util:                  1.01
    Test::Simple:                  0
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
