# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-Pattern
version:      0.26
version_from: Pattern.pm
installdirs:  site
requires:
    Chemistry::Mol:                0.24
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
